USE CafeRestaurant;

SELECT CONSTRAINT_NAME 
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
WHERE TABLE_NAME = 'WaiterCalls' AND COLUMN_NAME = 'TableID' AND TABLE_SCHEMA = 'CafeRestaurant';
ALTER TABLE WaiterCalls DROP FOREIGN KEY waitercalls_ibfk_1;

ALTER TABLE WaiterCalls
ADD CONSTRAINT fk_waitercalls_tableid FOREIGN KEY (TableID) REFERENCES Tables(TableID) ON DELETE CASCADE;